import Navbar from "../navbar/navbar";
import Head from "next/dist/shared/lib/head";

export default function Container(props) {
  return (
    <div>
      <Navbar />
      <Head>
        <title>Vida Fit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
        />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/v4-shims.css"
        />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <div>{props.children}</div>
    </div>
  );
}
